session/urls.py
from django.urls import path
from . import views

app_name = "session"

urlpatterns = [
    path("therapist/list/", views.TherapistListView.as_view(), name="therapist_list"),
    path("session/start/therapist/<int:therapist_id>/", views.CreateSessionView.as_view(),
         name="start_session_with_therapist"),
    path("thread/<int:thread_id>/", views.MessageThreadView.as_view(), name="message_thread"),
    path("inbox/", views.InboxView.as_view(), name="inbox_view")
]

therapy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from profiles.views import index, contact, about

urlpatterns = [
    path("", index, name="home"),
    path("index.html", index, name="home"),
    path("contact.html", contact, name="contact_page"),
    path("about.html", about, name="about_page"),
    path('admin/', admin.site.urls),
    path("profiles/", include("profiles.urls")),
    path("session/", include("session.urls")),
    path("accounts/", include("django.contrib.auth.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

session/models.py
from django.db import models
from django_extensions.db.models import TimeStampedModel
from profiles.models import Therapist, Patient
from author.decorators import with_author
from djchoices import ChoiceItem, DjangoChoices


# Create your models here.
@with_author
class TherapySession(TimeStampedModel):
    class SessionStates(DjangoChoices):
        progress = ChoiceItem("Progress")
        complete = ChoiceItem("Complete")
    therapist = models.ForeignKey(Therapist, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    status = models.CharField(choices=SessionStates.choices, default=SessionStates.progress, max_length=10)

session/forms.py
from django import forms
from pinax.messages.models import Message


class NewMessageForm(forms.Form):
    subject = forms.CharField()
    content = forms.CharField(widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        self.sender = kwargs.pop("sender")
        self.recipient = kwargs.pop("recipient")
        super(NewMessageForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        data = self.cleaned_data
        return Message.new_message(
            self.sender, [self.recipient], data["subject"], data["content"]
        )


class MessageReplyForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.thread = kwargs.pop("thread")
        self.user = kwargs.pop("user")
        super(MessageReplyForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        return Message.new_reply(
            self.thread, self.user, self.cleaned_data["content"]
        )

    class Meta:
        model = Message
        fields = ["content"]

session/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, View, TemplateView
from pinax.messages.models import Message, Thread

from profiles.models import Therapist


# Create your views here.
class TherapistListView(ListView):
    model = Therapist
    queryset = Therapist.objects.all()
    template_name = "session/therapist_list.html"


class CreateSessionView(View):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CreateSessionView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        therapist = Therapist.objects.get(id=self.kwargs["therapist_id"])
        subject = "Therapy between {} and {}".format(self.request.user.first_name, therapist.user.first_name)
        content = "Hello {}, I would like to have a session with you.".format(therapist.user.get_full_name())
        thread = None
        for t in self.request.user.userthread_set.all():
            if therapist.user in t.thread.users.all():
                thread = t.thread
        if thread is None:
            message = Message.new_message(from_user=self.request.user, to_users=[therapist.user,], subject=subject, content=content)
            thread = message.thread
        url = reverse_lazy("session:message_thread", args=[thread.id])
        return redirect(url)


class MessageThreadView(View):

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MessageThreadView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        thread = get_object_or_404(Thread, id=self.kwargs["thread_id"])
        thread.userthread_set.filter(user=self.request.user).update(unread=False)
        threads = []
        for t in Thread.objects.all():
            if self.request.user in t.users.all():
                threads.append(t)
        context = {
            "thread_active": thread,
            "recipient": thread.users.all()[0].get_full_name(),
            "threads": threads,
            "threads_unread": Thread.ordered(Thread.unread(self.request.user))
        }
        return render(self.request, "session/thread.html", context)

    def post(self, request, *args, **kwargs):
        thread = get_object_or_404(Thread, id=self.kwargs["thread_id"])
        content = str(self.request.POST.get("content")).strip()
        if content is not None or content != "":
            Message.new_reply(thread=thread, user=self.request.user, content=content)
        # return redirect(self.request.path)
        return self.get(self.request, *args, **kwargs)


class InboxView(TemplateView):
    """
    View inbox thread list.
    """
    # template_name = "session/inbox.html"
    template_name = "session/thread.html"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(InboxView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(InboxView, self).get_context_data(**kwargs)
        thread = Thread.ordered(Thread.inbox(self.request.user))[-1]
        thread.userthread_set.filter(user=self.request.user).update(unread=False)
        threads = []
        for t in Thread.objects.all():
            if self.request.user in t.users.all():
                threads.append(t)
        context.update({
            "thread_active": thread,
            "recipient": thread.users.all()[0].get_full_name(),
            "threads": threads,
            "threads_unread": Thread.ordered(Thread.unread(self.request.user))
        })
        return context

templates/session/inbox.html
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js" type="text/javascript"></script>

Welcome {{ request.user.get_full_name }}

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Subject</th>
            <th scope="col">Content</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
    {% for thread in threads %}
        <tr>
            <td>{{ thread.subject }}</td>
            <td>{{ thread.latest_message.content|truncatewords:5 }}</td>
        </tr>
    {% endfor %}
     <thead>
        <tr>
            <th scope="col">Subject</th>
            <th scope="col">Content</th>
        </tr>
    </thead>
</table>

templates/session/new_message_form.html
<h3>Start session with {{ recipient.user.get_full_name }}</h3>
<form method="post" action="">
    {% csrf_token %}
    {{ form.text }}
    <input type="hidden" value="{{ recipient.id }}" name="recipient">
    <input type="submit" value="Submit">
</form>

templates/session/therapist_list.html
<h4>List of therapists</h4>
{% for therapist in therapist_list %}
    Name : {{ therapist.user.get_full_name }}
    {% if request.user.is_authenticated %}
        <a href="{% url "session:start_session_with_therapist" therapist.id %}">Start session</a>
    {% endif %}
    {% if therapist.gender is not None %}
        Gender : {{ therapist.gender }}
    {% endif %}
    {% if therapist.date_of_birth is not None %}
        Age : {{ therapist.get_age }}
    {% endif %}
    {% if therapist.telephone is not None %}
        Phonenumber : {{ therapist.telephone }}
    {% endif %}
    {% if therapist.description is not None %}
        Description : {{ therapist.description }}
    {% endif %}
    {% if therapist.picture.url is not None %}
        <img src="{{ therapist.picture.url }}" width="50px" height="50px"/>
    {% endif %}
{% endfor %}